//@version=4
// Author: Akash Sasikumar
// Copyright: 2023.Akash sasikumar

study("Adaptive Moving Average", shorttitle="AMA", overlay=true)

length = input(title="Length", type=input.integer, defval=14)
fastLength = input(title="Fast EMA Length", type=input.integer, defval=2)
slowLength = input(title="Slow EMA Length", type=input.integer, defval=30)
highlightMovements = input(title="Highlight Movements ?", type=input.bool, defval=true)
src = input(title="Source", type=input.source, defval=close)

fastAlpha = 2 / (fastLength + 1)
slowAlpha = 2 / (slowLength + 1)

hh = highest(length + 1)
ll = lowest(length + 1)

mltp = hh - ll != 0 ? abs(2 * src - ll - hh) / (hh - ll) : 0

ssc = mltp * (fastAlpha - slowAlpha) + slowAlpha

var ama = 0.0
ama := na(ama[1]) ? pow(ssc, 2) * src : pow(ssc, 2) * src + (1 - pow(ssc, 2)) * ama[1]

amaColor = highlightMovements ? (ama > ama[1] ? color.rgb(40, 226, 255) : color.rgb(110, 14, 255)) : color.purple
plot(ama, title="AMA", linewidth=2, color=amaColor, transp=0)