//@version=4
// Author: Akash Sasikumar
// Copyright: 2023.Akash sasikumar

study("SuperTrend Indicator", shorttitle = "STI", overlay = true)

bool1 = input(true, title = "Line 1")
atr1len = input(10, minval = 1, title = "ATR period")
multiplier1 = input(1, minval = 0.1, title = "ATR multiplier")
bool2 = input(true, title = "Line 2")
atr2len = input(11, minval = 1, title = "ATR period")
multiplier2 = input(2, minval = 0.1, title = "ATR multiplier")
bool3 = input(true, title = "Line 3")
atr3len = input(12, minval = 1, title = "ATR period")
multiplier3 = input(3, minval = 0.1, title = "ATR multiplier")

atr1 = atr(atr1len)
atr2 = atr(atr2len)
atr3 = atr(atr3len)
sma = plot(sma(hl2, 1), color = color.white, title = "0", display = display.none)

up_one = hl2 - atr1 * multiplier1
up1_one = up_one[1]
up_one := close[1] > up1_one ? max(up_one, up1_one) : up_one
down_one = hl2 + atr1 * multiplier1
down1_one = down_one[1]
down_one := close[1] < down1_one ? min(down_one, down1_one) : down_one
trendup_one = crossover(close, down1_one) 
trenddown_one = crossunder(close, up1_one) 
var trend_one = 0
if (trendup_one) 
    trend_one := 1
if (trenddown_one) 
    trend_one := -1
buysignal1 = trend_one == 1 and trend_one[1] == -1
sellsignal1 = trend_one == -1 and trend_one[1] == 1

greenline1 = plot(trend_one == 1 and bool1 ? up_one : na, style = plot.style_linebr, color = color.green, linewidth = 2, title = "1")
redline1 = plot(trend_one == -1 and bool1 ? down_one : na, style = plot.style_linebr, color = color.red, linewidth = 2, title = "1")
fill(greenline1, sma, color = color.green)
fill(redline1, sma, color = color.red)
plotshape(buysignal1 and bool1 ? up_one : na, style = shape.circle, location = location.absolute, size = size.tiny, color = color.green)
plotshape(sellsignal1 and bool1 ? down_one : na, style = shape.circle, location = location.absolute, size = size.tiny, color = color.red)

up_two = hl2 - atr2 * multiplier2
up1_two = up_two[1]
up_two := close[1] > up1_two ? max(up_two, up1_two) : up_two
down_two = hl2 + atr2 * multiplier2
down1_two = down_two[1]
down_two := close[1] < down1_two ? min(down_two, down1_two) : down_two
trendup_two = crossover(close, down1_two) 
trenddown_two = crossunder(close, up1_two) 
var trend_two = 0
if (trendup_two) 
    trend_two := 1
if (trenddown_two) 
    trend_two := -1
buysignal2 = trend_two == 1 and trend_two[1] == -1
sellsignal2 = trend_two == -1 and trend_two[1] == 1
    
greenline2 = plot(trend_two == 1 and bool2 ? up_two : na, style = plot.style_linebr, color = color.green, linewidth = 2, title = "2")
redline2 = plot(trend_two == -1 and bool2 ? down_two : na, style = plot.style_linebr, color = color.red, linewidth = 2, title = "2")
fill(greenline2, sma, color = color.green)
fill(redline2, sma, color = color.red)
plotshape(buysignal2 and bool2 ? up_two : na, style = shape.circle, location = location.absolute, size = size.tiny, color = color.green)
plotshape(sellsignal2 and bool2 ? down_two : na, style = shape.circle, location = location.absolute, size = size.tiny, color = color.red)

up_three = hl2 - atr3 * multiplier3
up1_three = up_three[1]
up_three := close[1] > up1_three ? max(up_three, up1_three) : up_three
down_three = hl2 + atr3 * multiplier3
down1_three = down_three[1]
down_three := close[1] < down1_three ? min(down_three, down1_three) : down_three
trendup_three = crossover(close, down1_three) 
trenddown_three = crossunder(close, up1_three) 
var trend_three = 0
if (trendup_three) 
    trend_three := 1
if (trenddown_three) 
    trend_three := -1
buysignal3 = trend_three == 1 and trend_three[1] == -1
sellsignal3 = trend_three == -1 and trend_three[1] == 1
    
greenline3 = plot(trend_three == 1 and bool3 ? up_three : na, style = plot.style_linebr, color = color.green, linewidth = 2, title = "3")
redline3 = plot(trend_three == -1 and bool3 ? down_three : na, style = plot.style_linebr, color = color.red, linewidth = 2, title = "3")
fill(greenline3, sma, color = color.green)
fill(redline3, sma, color = color.red)
plotshape(buysignal3 and bool3 ? up_three : na, style = shape.circle, location = location.absolute, size = size.tiny, color = color.green)
plotshape(sellsignal3 and bool3 ? down_three : na, style = shape.circle, location = location.absolute, size = size.tiny, color = color.red)