//@version=3
// Author: Akash Sasikumar
// Copyright: 2023.Akash sasikumar

study("Trend Strength Index by Tradingene", shorttitle="TSI")
length = input(30, title="Length")
smoothing = input(5, title="Smoothing")


volatility = sum(abs(close[1]-close[2]), length)
change = abs(close[1]-close[length+1])
tsi = iff(volatility != 0, change/volatility, 0)



plot(sma(tsi, smoothing), color=red, title="TSI")
plot(sma(tsi, 100), color=black, title="TSI sm")